import type { Metadata } from "next";
import { montserrat400 } from "../fonts/montserrat";
import NextAuthProvider from "@/providers/authProvider";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/reactQueryProvider";
import Header from "@/components/app/header";
export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth();

    return (
        <ReactQueryProvider>
            <NextAuthProvider session={session}>
                <main
                    className={`${montserrat400.className} antialiased min-h-screen overflow-hidden relative`}
                >
                    <Header />
                    {children}
                    <Toaster />
                </main>
            </NextAuthProvider>
        </ReactQueryProvider>
    );
}
