import type { Metadata } from "next";
import "./globals.css";
import { montserrat400 } from "./fonts/montserrat";
import NextAuthProvider from "@/providers/authProvider";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/reactQueryProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <ReactQueryProvider>
        <NextAuthProvider session={session}>
          <body
            className={`${montserrat400.className} antialiased min-h-screen overflow-hidden relative`}
          >
            {children}
            <Toaster />
          </body>
        </NextAuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
