apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cademy-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: karthikrdy150502@gmail.com
    privateKeySecretRef:
      name: cademy-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
