apiVersion: v1
kind: Service
metadata:
  name: cademy-server-clusterip
spec:
  selector:
    app: cademy-server
  ports:
    - protocol: TCP
      port: 8001 # Service port
      targetPort: 8001 # Container port
  type: ClusterIP
