apiVersion: v1
kind: Service
metadata:
  name: cademy-ws-clusterip
spec:
  selector:
    app: cademy-ws
  ports:
    - protocol: TCP
      port: 8002 # Service port
      targetPort: 8002 # Container port
  type: ClusterIP
