name: Build and deploy Node backend to dockerhub
on: 
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to the Docker Hub account
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}     
          password: ${{ secrets.DOCKER_PASSWORD }}     
      
      - name: Build and Push docker image
        uses: docker/build-push-action@v2
        with:
          context: server
          build-args: |   
              AUTH_SECRET=${{ secrets.AUTH_SECRET }}
              DATABASE_URL=${{ secrets.DATABASE_URL }}
              NEXT_PUBLIC_LIVEKIT_API_KEY=${{ secrets.NEXT_PUBLIC_LIVEKIT_API_KEY }}
              NEXT_PUBLIC_LIVEKIT_API_SECRET=${{ secrets.NEXT_PUBLIC_LIVEKIT_API_SECRET }}
              NEXT_PUBLIC_LIVEKIT_WS_URL=${{ secrets.NEXT_PUBLIC_LIVEKIT_WS_URL }}
          file: ./server/Dockerfile
          push: true
          tags: karthik150502/cademy_server:latest

      - name: Verify pushed image
        run: docker pull karthik150502/cademy_server:latest